products = [
    {
      '_id': '1',
      'name': 'Apple AirpodsPro Wireless Headphones',
      'image': '/images/airpods2.jpg',
      'description':
        'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working.',
      'brand': 'Apple',
      'category': 'Electronics',
      'price': 99.99,
      'countInStock': 10,
      'rating': 4.5,
      'numReviews': 50,
    },
    {
      '_id': '2',
      'name': 'Apple Macbook Air 2020',
      'image': '/images/mba.jpg',
      'description':
        'Our thinnest, lightest notebook, completely transformed by the Apple M1 chip. CPU speeds up to 3.5x faster. GPU speeds up to 5x faster. Our most advanced Neural Engine for up to 9x faster machine learning. The longest battery life ever in a MacBook Air. And a silent, fanless design. This much power has never been this ready to go.',
      'brand': 'Apple',
      'category': 'Electronics',
      'price': 899.99,
      'countInStock': 7,
      'rating': 5,
      'numReviews': 8,
    },
    {
      '_id': '3',
      'name': 'Apple Macbook Pro 2020',
      'image': '/images/mb_pro.jpg',
      'description':
        'The Apple M1 chip gives the 13‑inch MacBook Pro speed and power beyond belief. With up to 2.8x CPU performance. Up to 5x the graphics speed. Our most advanced Neural Engine for up to 11x faster machine learning. And up to 20 hours of battery life — the longest of any Mac ever. It’s our most popular pro notebook, taken to a whole new level.',
      'brand': 'Apple',
      'category': 'Electronics',
      'price': 1199.99,
      'countInStock': 5,
      'rating': 4,
      'numReviews': 12,
    },
    {
      '_id': '4',
      'name': 'Apple Airpods Wireless Headphones',
      'image': '/images/airpods1.jpg',
      'description':
        'With more talk time, voice-activated Siri access — and a wireless charging case — AirPods deliver an unparalleled wireless headphone experience. Simply take them out and they’re ready to use with all your devices. Put them in your ears and they connect immediately, immersing you in rich, high-quality sound. Just like magic.',
      'brand': 'Apple',
      'category': 'Electronics',
      'price': 99.99,
      'countInStock': 20,
      'rating': 3.9,
      'numReviews': 12,
    },
    {
      '_id': '5',
      'name': 'Microsoft Xbox Series X Disk Version',
      'image': '/images/xboxx.jpg',
      'description':
        'The 12 teraflops of processing power housed in the system on a chip (SOC) work with AMD’s Zen 2 and RDNA 2 architectures to result in worlds that demand a closer look. The Xbox Series X delivers sensationally smooth frame rates of up to 120FPS with the visual pop of HDR. Immerse yourself with sharper characters, brighter worlds, and impossible details with true-to-life 4K.',
      'brand': 'Microsoft',
      'category': 'Electronics',
      'price': 399.99,
      'countInStock': 7,
      'rating': 4,
      'numReviews': 10,
    },
    {
      '_id': '6',
      'name': 'Sony Playstation 5 Disk Version',
      'image': '/images/ps5.jpg',
      'description':
        'Experience lightning-fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers and 3D Audio*, and an all-new generation of incredible PlayStation® games.',
      'brand': 'Sony',
      'category': 'Electronics',
      'price': 499.99,
      'countInStock': 0,
      'rating': 4.75,
      'numReviews': 200,
    },
    {
      '_id': '7',
      'name': 'Nintendo Switch Neon Joy-Cons',
      'image': '/images/nintendo_switch.jpg',
      'description':
        'Nintendo Switch is designed to fit your life, transforming from home console to portable system in a snap. Dock your Nintendo Switch to enjoy HD gaming on your TV. Pick it up and play with the Joy‑Con™ controllers attached.',
      'brand': 'Nintendo',
      'category': 'Electronics',
      'price': 199.99,
      'countInStock': 4,
      'rating': 4,
      'numReviews': 145,
    },
    {
      '_id': '8',
      'name': 'ASUS ROG Zephyrus Duo 15 SE GX551',
      'image': '/images/asus.jpg',
      'description':
        'With its innovative ROG ScreenPad Plus secondary display, the Zephyrus Duo 15 SE takes Windows 10 gaming to new dimensions. Cutting-edge cooling empowers the latest AMD Ryzen™ 9 5900HX CPU and NVIDIA® GeForce RTX™ 3080 GPU. A choice between ultrafast 300Hz/3ms or high-res 4K 120Hz/3ms gaming panels lets you tailor your system for pro-level esports or content creation. Elevate your entire experience with premium audio delivered by quad speakers and immersive Dolby Atmos surround sound.',
      'brand': 'Asus',
      'category': 'Electronics',
      'price': 2999.99,
      'countInStock': 9,
      'rating': 4,
      'numReviews': 56,
    },
  ]
  
